name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare for tests
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install -r ./securities-microservice/requirements.txt
          docker build . --file ./securities-microservice/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/microservice:latest
          docker run -p 80:80 -d ${{ secrets.DOCKER_USERNAME }}/microservice:latest
          sleep 5
      - name: Run tests
        run: |
          pytest ./securities-microservice/integrat.py
          pytest ./securities-microservice/component.py

  build:
    needs: [ test ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./securities-microservice --tag rattokun/microservice:latest
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Tag to Dockerhub
      run: docker push rattokun/microservice
